BUNDLES-165 Enable multiple entry points to generate css classes
softspring/cms-bundle pull request #28
Opened 2023-02-24 08:19 UTC by evabelpeq

2023-02-24 08:22 UTC, AritzPalaciosOrtiz submitted a review, later dismissed

2023-02-24 08:47 UTC, AnaHuergoP approved these changes, later dismissed

2023-02-28 14:23 UTC, javihgil requested changes

2023-02-28 14:23 UTC, javihgil commented on assets/scripts/admin/content-edit/preview-class.js
> +            htmlTargetElements[0].className = classesElement;
This code (htmlTargetElements[0].className = classesElement;) breaks the multiple target assignment made by: let htmlInputsElements = moduleForm.querySelectorAll("[data-edit-class-input='" + event.target.dataset.editClassInput + "']");. 

We should not lost this feature.

2023-02-28 15:18 UTC, javihgil approved these changes

2023-02-28 15:42 UTC, merged